"""Stable state contracts for the AI Migration Control Tower domain."""

from __future__ import annotations

from enum import Enum


class JobState(str, Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    PAUSED_FOR_PLAN_APPROVAL = "PAUSED_FOR_PLAN_APPROVAL"
    PAUSED_FOR_REPAIR = "PAUSED_FOR_REPAIR"
    RESUMING = "RESUMING"
    CANCELLING = "CANCELLING"
    ORPHANED = "ORPHANED"
    RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class StageState(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    PASSED = "PASSED"
    PASSED_WITH_WARNINGS = "PASSED_WITH_WARNINGS"
    FAILED = "FAILED"
    SKIPPED_BY_POLICY = "SKIPPED_BY_POLICY"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class TargetProofLevel(str, Enum):
    ANALYZED = "ANALYZED"
    PLANNED = "PLANNED"
    TRANSFORMED = "TRANSFORMED"
    BUILD_TEST_VERIFIED = "BUILD_TEST_VERIFIED"
    RUNTIME_VERIFIED = "RUNTIME_VERIFIED"
    ENDPOINT_VERIFIED = "ENDPOINT_VERIFIED"
