"""Shared contracts used by Migration Factory agents."""

from migration_factory.contracts.constants import (
    ALL_REQUIRED_ARTIFACTS,
    ANALYSIS_OPTIONAL_ARTIFACTS,
    ANALYSIS_REQUIRED_ARTIFACTS,
    APPROVAL_DECISION_VALUES,
    ASSESSMENT_REQUIRED_ARTIFACTS,
    COPILOT_STATUS_VALUES,
    DIRECTORY_NAMES,
    PLANNING_OPTIONAL_ARTIFACTS,
    PLANNING_REQUIRED_ARTIFACTS,
    RISK_VALUES,
    SCHEMA_VERSION,
    STATUS_VALUES,
)
from migration_factory.contracts.planning_assist import (
    AssistResultStatus,
    PlanningAssistRequest,
    PlanningAssistResult,
)
from migration_factory.contracts.planning_artifacts import (
    OPTIONAL_ANALYSIS_INPUT_ARTIFACTS,
    PLANNING_OUTPUT_ARTIFACTS,
    REQUIRED_ANALYSIS_INPUT_ARTIFACTS,
)
from migration_factory.contracts.assessment_artifacts import (
    ASSESSMENT_OUTPUT_ARTIFACTS,
    OPTIONAL_ASSESSMENT_INPUT_ARTIFACTS,
    REQUIRED_ASSESSMENT_INPUT_ARTIFACTS,
)
__all__ = [
    "SCHEMA_VERSION",
    "DIRECTORY_NAMES",
    "ANALYSIS_REQUIRED_ARTIFACTS",
    "ANALYSIS_OPTIONAL_ARTIFACTS",
    "PLANNING_REQUIRED_ARTIFACTS",
    "PLANNING_OPTIONAL_ARTIFACTS",
    "ASSESSMENT_REQUIRED_ARTIFACTS",
    "ALL_REQUIRED_ARTIFACTS",
    "STATUS_VALUES",
    "RISK_VALUES",
    "APPROVAL_DECISION_VALUES",
    "COPILOT_STATUS_VALUES",
    "AssistResultStatus",
    "PlanningAssistRequest",
    "PlanningAssistResult",
    "REQUIRED_ANALYSIS_INPUT_ARTIFACTS",
    "OPTIONAL_ANALYSIS_INPUT_ARTIFACTS",
    "PLANNING_OUTPUT_ARTIFACTS",
    "REQUIRED_ASSESSMENT_INPUT_ARTIFACTS",
    "OPTIONAL_ASSESSMENT_INPUT_ARTIFACTS",
    "ASSESSMENT_OUTPUT_ARTIFACTS",
]
