from migration_factory.contracts.constants import (
    ANALYSIS_OPTIONAL_ARTIFACTS,
    ANALYSIS_REQUIRED_ARTIFACTS,
    ASSESSMENT_REQUIRED_ARTIFACTS,
    PLANNING_OPTIONAL_ARTIFACTS,
    PLANNING_REQUIRED_ARTIFACTS,
)


REQUIRED_ASSESSMENT_INPUT_ARTIFACTS = (
    *ANALYSIS_REQUIRED_ARTIFACTS,
    *PLANNING_REQUIRED_ARTIFACTS,
)

OPTIONAL_ASSESSMENT_INPUT_ARTIFACTS = (
    *ANALYSIS_OPTIONAL_ARTIFACTS,
    *PLANNING_OPTIONAL_ARTIFACTS,
)

ASSESSMENT_OUTPUT_ARTIFACTS = ASSESSMENT_REQUIRED_ARTIFACTS
