from migration_factory.contracts.constants import (
    ANALYSIS_OPTIONAL_ARTIFACTS,
    ANALYSIS_REQUIRED_ARTIFACTS,
    PLANNING_OPTIONAL_ARTIFACTS,
    PLANNING_REQUIRED_ARTIFACTS,
)

REQUIRED_ANALYSIS_INPUT_ARTIFACTS = ANALYSIS_REQUIRED_ARTIFACTS
OPTIONAL_ANALYSIS_INPUT_ARTIFACTS = ANALYSIS_OPTIONAL_ARTIFACTS

PLANNING_OUTPUT_ARTIFACTS = (
    *PLANNING_REQUIRED_ARTIFACTS,
    *PLANNING_OPTIONAL_ARTIFACTS,
)
